# Generated by Django 4.2.7 on 2023-11-23 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies_app', '0002_rename_collections_movie_collection'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenreCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre_name', models.CharField(max_length=100)),
                ('genre_count', models.IntegerField(default=0)),
                ('collection_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies_app.collection')),
            ],
        ),
        migrations.RemoveField(
            model_name='movie',
            name='genres',
        ),
        migrations.DeleteModel(
            name='Genre',
        ),
        migrations.AddField(
            model_name='movie',
            name='genres',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
