# Generated by Django 4.2.7 on 2023-11-23 18:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies_app', '0003_genrecount_remove_movie_genres_delete_genre_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genrecount',
            name='collection_id',
        ),
        migrations.AddField(
            model_name='genrecount',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
