# Generated by Django 4.2.7 on 2023-11-23 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies_app', '0004_remove_genrecount_collection_id_genrecount_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genrecount',
            name='user',
        ),
        migrations.AddField(
            model_name='genrecount',
            name='user_id',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='genrecount',
            name='genre_count',
            field=models.IntegerField(default=1),
        ),
    ]
