# Generated by Django 4.2.7 on 2023-11-23 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies_app', '0005_remove_genrecount_user_genrecount_user_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='collection',
            field=models.ManyToManyField(related_name='movies', to='movies_app.collection'),
        ),
    ]
