# Generated by Django 4.2.7 on 2023-11-23 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies_app', '0006_alter_movie_collection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='collection',
            field=models.ManyToManyField(to='movies_app.collection'),
        ),
    ]
