# Generated by Django 4.2.7 on 2023-11-24 09:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('movies_app', '0007_alter_movie_collection'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
